---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2024/7/23 10:26
---
TypeInfo = {
    Canvas = typeof(UnityEngine.Canvas),
    Camera = typeof(UnityEngine.Camera),
    GameObject = typeof(UnityEngine.GameObject),
    Material = typeof(UnityEngine.Material),
    RectTransform = typeof(UnityEngine.RectTransform),
    CanvasGroup = typeof(UnityEngine.CanvasGroup),


    Image = typeof(UnityEngine.UI.Image),
    ScrollRect = typeof(UnityEngine.UI.ScrollRect),

    TextMeshProUGUI = typeof(TMPro.TextMeshProUGUI),
    TextMeshProUGUI = typeof(TMPro.TextMeshPro),

    DOTweenAnimation = typeof(DG.Tweening.DOTweenAnimation),
}