---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by VIVA.
--- DateTime: 2023/12/31 16:58
--- 角色基本数据

local UserData = {}

UserData.userName = nil
UserData.copper = 0
UserData.food = 0
UserData.wood = 0
UserData.gold = 0
UserData.tieqi = 0


UserData.generalHash = {}

return UserData