---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2024/3/23 14:02
--- 倒计时时间
---@class CountDownTime
---@field New fun(time:number, unit:string):CountDownTime
local CountDownTime = class("CountDownTime")

function CountDownTime:Ctor(time, unit)
    unit = unit or TimeUtil.TYPE_S
    if unit ~= TimeUtil.TYPE_S then
        time = Happy.TimeConvert(unit, TimeUtil.TYPE_S, time)
    end
    self.dur = time
    self.startTime = Time.time
end

function CountDownTime:ChangeTime(time, unit)
    unit = unit or TimeUtil.TYPE_S
    if unit ~= TimeUtil.TYPE_S then
        time = Happy.TimeConvert(unit, TimeUtil.TYPE_S, time)
    end
    self.dur = self.dur + time
end

function CountDownTime:GetTime(unit)
    local returnTime = self.dur - (Time.time - self.startTime)
    if unit ~= TimeUtil.TYPE_S then
        returnTime = Happy.TimeConvert(TimeUtil.TYPE_S, unit, returnTime)
    end

    return unit
end

return CountDownTime