---@class UnityEngine.ParticleSystem.MainModule
---@field emitterVelocity UnityEngine.Vector3
---@field duration float
---@field loop bool
---@field prewarm bool
---@field startDelay UnityEngine.ParticleSystem.MinMaxCurve
---@field startDelayMultiplier float
---@field startLifetime UnityEngine.ParticleSystem.MinMaxCurve
---@field startLifetimeMultiplier float
---@field startSpeed UnityEngine.ParticleSystem.MinMaxCurve
---@field startSpeedMultiplier float
---@field startSize3D bool
---@field startSize UnityEngine.ParticleSystem.MinMaxCurve
---@field startSizeMultiplier float
---@field startSizeX UnityEngine.ParticleSystem.MinMaxCurve
---@field startSizeXMultiplier float
---@field startSizeY UnityEngine.ParticleSystem.MinMaxCurve
---@field startSizeYMultiplier float
---@field startSizeZ UnityEngine.ParticleSystem.MinMaxCurve
---@field startSizeZMultiplier float
---@field startRotation3D bool
---@field startRotation UnityEngine.ParticleSystem.MinMaxCurve
---@field startRotationMultiplier float
---@field startRotationX UnityEngine.ParticleSystem.MinMaxCurve
---@field startRotationXMultiplier float
---@field startRotationY UnityEngine.ParticleSystem.MinMaxCurve
---@field startRotationYMultiplier float
---@field startRotationZ UnityEngine.ParticleSystem.MinMaxCurve
---@field startRotationZMultiplier float
---@field flipRotation float
---@field startColor UnityEngine.ParticleSystem.MinMaxGradient
---@field gravityModifier UnityEngine.ParticleSystem.MinMaxCurve
---@field gravityModifierMultiplier float
---@field simulationSpace UnityEngine.ParticleSystemSimulationSpace
---@field customSimulationSpace UnityEngine.Transform
---@field simulationSpeed float
---@field useUnscaledTime bool
---@field scalingMode UnityEngine.ParticleSystemScalingMode
---@field playOnAwake bool
---@field maxParticles int
---@field emitterVelocityMode UnityEngine.ParticleSystemEmitterVelocityMode
---@field stopAction UnityEngine.ParticleSystemStopAction
---@field ringBufferMode UnityEngine.ParticleSystemRingBufferMode
---@field ringBufferLoopRange UnityEngine.Vector2
---@field cullingMode UnityEngine.ParticleSystemCullingMode
local m = {}
UnityEngine = {}
UnityEngine.ParticleSystem = {}
UnityEngine.ParticleSystem.MainModule = m
return m