---@class DG.Tweening.DOTweenAnimation : DG.Tweening.Core.ABSAnimationComponent
---@field targetIsSelf bool
---@field targetGO UnityEngine.GameObject
---@field tweenTargetIsTargetGO bool
---@field delay float
---@field duration float
---@field easeType DG.Tweening.Ease
---@field easeCurve UnityEngine.AnimationCurve
---@field loopType DG.Tweening.LoopType
---@field loops int
---@field id string
---@field isRelative bool
---@field isFrom bool
---@field isIndependentUpdate bool
---@field autoKill bool
---@field isActive bool
---@field isValid bool
---@field target UnityEngine.Component
---@field animationType DG.Tweening.DOTweenAnimation.AnimationType
---@field targetType DG.Tweening.DOTweenAnimation.TargetType
---@field forcedTargetType DG.Tweening.DOTweenAnimation.TargetType
---@field autoPlay bool
---@field useTargetAsV3 bool
---@field endValueFloat float
---@field endValueV3 UnityEngine.Vector3
---@field endValueV2 UnityEngine.Vector2
---@field endValueColor UnityEngine.Color
---@field endValueString string
---@field endValueRect UnityEngine.Rect
---@field endValueTransform UnityEngine.Transform
---@field optionalBool0 bool
---@field optionalFloat0 float
---@field optionalInt0 int
---@field optionalRotationMode DG.Tweening.RotateMode
---@field optionalScrambleMode DG.Tweening.ScrambleMode
---@field optionalString string
---@field updateType DG.Tweening.UpdateType
---@field isSpeedBased bool
---@field hasOnStart bool
---@field hasOnPlay bool
---@field hasOnUpdate bool
---@field hasOnStepComplete bool
---@field hasOnComplete bool
---@field hasOnTweenCreated bool
---@field hasOnRewind bool
---@field onStart UnityEngine.Events.UnityEvent
---@field onPlay UnityEngine.Events.UnityEvent
---@field onUpdate UnityEngine.Events.UnityEvent
---@field onStepComplete UnityEngine.Events.UnityEvent
---@field onComplete UnityEngine.Events.UnityEvent
---@field onTweenCreated UnityEngine.Events.UnityEvent
---@field onRewind UnityEngine.Events.UnityEvent
---@field tween DG.Tweening.Tween
local m = {}
function m:CreateTween() end
function m:DOPlay() end
function m:DOPlayBackwards() end
function m:DOPlayForward() end
function m:DOPause() end
function m:DOTogglePause() end
function m:DORewind() end
---@overload fun(fromHere:bool):void
function m:DORestart() end
function m:DOComplete() end
function m:DOKill() end
---@param id string
function m:DOPlayById(id) end
---@param id string
function m:DOPlayAllById(id) end
---@param id string
function m:DOPauseAllById(id) end
---@param id string
function m:DOPlayBackwardsById(id) end
---@param id string
function m:DOPlayBackwardsAllById(id) end
---@param id string
function m:DOPlayForwardById(id) end
---@param id string
function m:DOPlayForwardAllById(id) end
function m:DOPlayNext() end
function m:DORewindAndPlayNext() end
---@param id string
function m:DORewindAllById(id) end
---@param id string
function m:DORestartById(id) end
---@param id string
function m:DORestartAllById(id) end
---@return table
function m:GetTweens() end
---@param t System.Type
---@return DG.Tweening.DOTweenAnimation.TargetType
function m.TypeToDOTargetType(t) end
---@return DG.Tweening.Tween
function m:CreateEditorPreview() end
DG = {}
DG.Tweening = {}
DG.Tweening.DOTweenAnimation = m
return m