---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2018/5/19 下午3:40
---

require "LuaCore.functions"
require "LuaCore.define"
require "Game"

function Main()
     Game.Init()
end

local function errorHandler(msg)
     LogError("[lua error]\n"..msg, debug.traceback("", 2))
end

xpcall(Main, errorHandler)