---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2024/1/22 17:28
--- 唯一的引导之手
---@class GuideHand:LuaObj
---@field New fun():GuideHand
local GuideHand = class("GuideHand", LuaObj)

function GuideHand.TakeShow(gameObject, offsetV2, clickCall, rotZ)
    if not GuideHand.instance then
        GuideHand.instance = GuideHand.New()
    end
    GuideHand.instance:Show(gameObject, offsetV2, clickCall, rotZ)
end

function GuideHand:Ctor()
    GuideHand.super.Ctor(self, "Prefabs/Guide/GuideHand.prefab", nil, UILayerName.guide)
    self.rt = GetComponent.RectTransform(self.gameObject)
    self.handRt = GetComponent.RectTransform(self.transform:Find("GuideHand").gameObject)
    self.dt = GetComponent.DOTweenAnimation(self.transform:GetChild(0).gameObject)
    self.guideWorkerLv = -1
    self.guideCleanLv = -1
    self:Hide()
end

---@param gameObject UnityEngine.GameObject
---@param offsetV2 Vector2
---@param rotZ number
function GuideHand:Show(gameObject, offsetV2, clickCall, rotZ)
    GuideHand.super.Show(self)
    self.rt.anchoredPosition = Happy.WorldToRectPos(gameObject.transform.position, UILayerName.guide, true)

    self.dt:DORestart()
    if offsetV2 then
        self.rt.anchoredPosition = self.rt.anchoredPosition + offsetV2
    end
    if rotZ then
        self.rt.localEulerAngles = Vector3.New(0,0, rotZ)
    else
        self.rt.localEulerAngles = Vector3.zero
    end
    local downH
    downH = AddButtonHandler(gameObject, PointerHandler.DOWN, function()
        RemoveButtonHandler(gameObject, PointerHandler.DOWN, downH)
        self.rt.anchoredPosition = Vector2.zero
        self:Hide()
    end)
    local clickH
    clickH = AddButtonHandler(gameObject, PointerHandler.CLICK, function()
        RemoveButtonHandler(gameObject, PointerHandler.CLICK, clickH)
        if clickCall then
            clickCall()
        end
    end)
end

return GuideHand