---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/6/7 15:40
--- 功能解锁
local prefabPath = "Prefabs/Common/OpenFunctionView.prefab"
---@class OpenFunctionView
---@field New fun(data:table, targetAnchor:Vector2, callback:function ):OpenFunctionView
local OpenFunctionView = class("OpenFunctionView")

function OpenFunctionView.OpenFunc(data, targetAnchor, callback)
    if OpenFunctionView.ins == nil then
        OpenFunctionView.ins = OpenFunctionView.New()
    end
    OpenFunctionView.ins:Init(data, targetAnchor)
    OpenFunctionView.ins:Play(callback)
end

function OpenFunctionView:Ctor()
    self.gameObject = CreatePrefab(prefabPath, Constants.LAYER_ALERT)
    self.transform = self.gameObject.transform
    self.rect = GetComponent.RectTransform(self.gameObject)
    self.cg = GetComponent.CanvasGroup(self.gameObject)
    self.bgImg = GetComponent.Image(self.transform:Find("bg").gameObject)
    self.bgRect = GetComponent.RectTransform(self.transform:Find("bg").gameObject)
    self.cycleImg = GetComponent.Image(self.transform:Find("bg/cycleImage").gameObject)
    self.functionIcon = GetComponent.Image(self.transform:Find("functionIcon").gameObject)
    self.functionCg = GetComponent.CanvasGroup(self.transform:Find("functionIcon").gameObject)
    self.functionName = GetComponent.TextMeshProUGUI(self.transform:Find("functionIcon/functionName").gameObject)
    self.fx_light = self.transform:Find("fx_light").gameObject
    self.fx_light_show = self.transform:Find("fx_light_show").gameObject
    self.titleText = GetComponent.TextMeshProUGUI(self.transform:Find("title").gameObject)
    self.titleTMPEffect = AddOrGetComponent(self.titleText.gameObject, TMPEffect) ---@type TMPEffect
    self.nameTMPEffect = AddOrGetComponent(self.functionName.gameObject, TMPEffect) ---@type TMPEffect
    self.bgOrgSize = self.bgRect.sizeDelta
    self.nameOrgColor = self.functionName.color
end

function OpenFunctionView:Init(data, targetAnchor)
    self.gameObject:SetActive(true)
    self.data = data
    self.targetAnchor = targetAnchor
    self.transform.localPosition = Vector3.New(0, 280, 0)
    self.bgRect.sizeDelta = Vector2.New(self.bgOrgSize.x, 0)
    self.functionCg.alpha = 0
    self.cycleImg.color = Color.clear
    self.cycleImg.transform.localScale = Vector3.one
    self.bgImg.color = Color.black
    self.titleText.text = ""
    self.titleText.color = Color.New(1, 224/255, 0, 1)
    self.fx_light:SetActive(false)
    self.fx_light_show:SetActive(false)
    self.functionName.color = self.nameOrgColor
    self.cg.alpha = 1
    self.funcName = self.functionName.text
    self.functionName.text = ""
    if self.data then
        if self.data.iconPath then
            self.functionIcon.sprite = resMgr:LoadSpriteAtPath(self.data.iconPath)
        end
        if self.data.name then
            self.funcName = self.data.name
        end
    end

end

function OpenFunctionView:Play(callback)
    --AudioManager.PlayAudio("unlock_function", 0.8)
    local seq = DOTween.Sequence()
    seq:AppendCallback(function()
        Happy.DOTweenFloat(0, self.bgOrgSize.y, 0.4, function(value)
            self.bgRect.sizeDelta = Vector2.New(self.bgOrgSize.x, value)
        end, function()
        self.bgRect.sizeDelta = self.bgOrgSize
        end)
    end)
    seq:Append(self.cycleImg:DOColor(Color.white, 0.4):SetEase(DOTWEEN_EASE.Linear))
    seq:AppendCallback(function()
        self.titleTMPEffect:PlayFadingType("功能解锁", 0.1)
    end)
    seq:AppendInterval(0.4)
    seq:Append(self.cycleImg:DOColor(Color.clear, 0.3):SetEase(DOTWEEN_EASE.Linear))
    --seq:Join(self.cycleImg.transform:DOScale(1.7, 0.3):SetEase(DOTWEEN_EASE.Linear))
    seq:AppendCallback(function()
        self.fx_light:SetActive(false)
        self.fx_light:SetActive(true)
    end)
    seq:Append(self.functionCg:DOFade(1, 0.35))
    seq:AppendCallback(function()
        self.nameTMPEffect:PlayFadingType(self.funcName, 0.15)
    end)
    seq:AppendInterval(1.4)
    if self.targetAnchor then
        ---飞向目标点
        seq:Append(self.bgImg:DOColor(Color.clear, 0.35))
        seq:Join(self.titleText:DOColor(Color.clear, 0.35))
        seq:Join(self.functionName:DOColor(Color.clear, 0.35))
        seq:Append(self.rect:DOAnchorPos(self.targetAnchor, 0.65):SetEase(DOTWEEN_EASE.InCubic))
        seq:AppendCallback(function()
            self.functionCg.alpha = 0
            self.fx_light_show:SetActive(false)
            self.fx_light_show:SetActive(true)
            --AudioManager.PlayAudio("unlock_success")
            if callback then callback() end
        end)
        seq:AppendInterval(1.5)
        seq:AppendCallback(function()
            --self.gameObject:SetActive(false)
            RecyclePrefab(self.gameObject, prefabPath)
        end)
    else
        ---渐隐消失
        seq:Append(self.cg:DOFade(0, 0.35))
        seq:AppendCallback(function()
            self.gameObject:SetActive(false)
            if callback then callback() end
        end)
    end

end

return OpenFunctionView