---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2024/6/15 14:32
--- ResManager接口整合
Audio = {}

function Audio.PlayEffect(path, volume)
    audioMgr:PlayEffectAudio(path, volume or 1)
end

function Audio.PlayBgm(path, volume)
    audioMgr:PlayBGM(path, volume or 1)
end

function Audio.Stop()

end

function Audio.StopAllBgm()

end

function Audio.StopAllEffect()

end

function Audio.IsPlaying()

end

return Audio