---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2024/6/15 14:10
--- ResManager接口整合
Res = {}

function Res.LoadSprite(path)
    return resMgr:LoadSpriteAtPath(path)
end

function Res.LoadAsset(path)
    return resMgr:LoadAssetAtPath(path)
end

return Res