---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2020-05-26 17:46
--- JSON

local cjson = require("cjson")
local JSON = {}



function JSON.decode(text)
    local status, result = pcall(cjson.decode, text)

    return result
end


function JSON.encode(value)
    local status, result = pcall(cjson.encode, value)

    return result
end

return JSON