---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/4/23 16:08
--- 支持寻路的Avatar

local BehaviorAvatar = require("Module.Common.View.AvatarBaseClass.BehaviorAvatar")
local AvatarBase = require("Module.Common.View.AvatarBaseClass.AvatarBase")
---@class PathFinderAvatar:AvatarBase
---@field New fun(prefabPath:string, parent:UnityEngine.Transform):PathFinderAvatar
local PathFinderAvatar = class("PathFinderAvatar", AvatarBase)

local DEFAULT_SPEED_SCALE = 1
local ANI_FIX_SCALE = 0.5
function PathFinderAvatar:Ctor(prefabPath, parent)
    PathFinderAvatar.super.Ctor(self, prefabPath, parent)

    self.seekerToLua = AddOrGetComponent(self.gameObject, SeekerToLua) ---@type SeekerToLua

    --do return end
    self.aiPath = AddOrGetComponent(self.gameObject, AIPathToLua) ---@type AIPathToLua
    self.aiPath.maxSpeed = DEFAULT_SPEED_SCALE
    self.aiPath.canSearch = false
    self.aiPath.slowdownDistance = 0.05
    self.aiPath.endReachedDistance = 0.02
    self.aiPath.whenCloseToDestination = Pathfinding.CloseToDestinationMode.Stop
    self.aiPath.rotationSpeed = 3000
    self.aiPath.slowWhenNotFacingTarget = false
    self.aiPath.groundMask = LayerMask.GetMask("Ground")
    self.aiPath.radius = 0
    self.aiPath:SetLuaCallBack(happyCall(self, self.MoveEnd))

    self.aiPath.enabled = false
end

---移动到指定位置(AStar)
---@param position Vector3 3D坐标 不是格子坐标
function PathFinderAvatar:MoveAStar(position, callBack, speedScale)
    if isnull(self.gameObject) == true then
        return
    end

    self:StopMoving(true)
    self.moving = true
    self.movingEndCall = callBack
    self.aiPath.maxSpeed = speedScale or DEFAULT_SPEED_SCALE

    self.aiPath.enabled = true
    self.goalPos = position
    self.seekerToLua:TakeMove(position, happyCall(self, self.GetPath))
end

---@param path Pathfinding.ABPath
function PathFinderAvatar:GetPath(path)
    local nodeList = path.path
    --print("PathFinderAvatar:GetPath 开始", nodeList.Count)
    if nodeList.Count == 1 then
        self:MoveEnd()
        return
    end

    self.aiPath.updateRotation = true
    self.aiPath.updatePosition = true
    self:PlayAnimation(AvatarBase.ANI_MOVE_NAME, 0.2)
    self.ani.speed = self.aiPath.maxSpeed/ANI_FIX_SCALE
end

function PathFinderAvatar:MoveEnd()
    self.aiPath.updateRotation = false
    self.aiPath.updatePosition = false
    self:PlayAnimation(AvatarBase.ANI_IDLE_NAME, 0.2)
    self.aiPath.maxSpeed = DEFAULT_SPEED_SCALE
    self.ani.speed = DEFAULT_SPEED_SCALE
    self.moving = false
    self.aiPath.enabled = false
    self.transform.position = self.goalPos
    self.goalPos = nil
    --self.ani.speed = 1
    if self.movingEndCall then
        local fun = self.movingEndCall
        self.movingEndCall = nil
        fun()
    end
end

function PathFinderAvatar:StopMoving(noMoveEndFun)
    self.aiPath:StopMove()
    if noMoveEndFun ~= true then
        self:MoveEnd()
    end
end

function PathFinderAvatar:Hide()
    PathFinderAvatar.super.Hide(self)
    if self.moving == true then
        self:MoveEnd()
    end
end

return PathFinderAvatar