---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2021/12/13 10:59
--- Behavior Designer 基础Action

---@class BaseAction
local BaseAction = class("BaseAction")


function BaseAction:Ctor(bToLua, cAction, paramFloat, paramBool)
    self.bToLua = bToLua ---@type BehaviorToLua
    self.cAction = cAction ---@type BehaviorDesigner.Runtime.Tasks.LuaAction
    self.paused = false
    self.paramFloat = paramFloat
    self.paramBool = paramBool
end

return BaseAction