---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2019-07-19 15:29
--- 用来绑定GameObject的回调
---@class LuaObj:LuaObj
---@field New fun(prefabPath:string, gameObject:UnityEngine.GameObject, parent:UnityEngine.Transform):LuaObj
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field component Prayer.OnDestroyHandler
local LuaObj = class("LuaObj")

---
function LuaObj:Ctor(prefabPath, gameObject, parent)
    self.prefabPath = prefabPath

    if type(parent) == "string" then
        parent = UIMgr.GetLayer(parent)
    end
    if prefabPath then
        self:BindGameObject(CreatePrefab(prefabPath, parent))
    elseif gameObject and not tolua.isnull(gameObject) then
        self:BindGameObject(gameObject, parent)
    end
end

function LuaObj:BindGameObject(gameObject, parent)
    self.gameObject = gameObject ---@type UnityEngine.GameObject
    self.transform = gameObject.transform ---@type UnityEngine.Transform
    if parent then
        if type(parent) == "string" then
            parent = UIMgr.GetLayer(parent)
        end
        local pos = self.transform.localPosition
        local scale = self.transform.localScale
        local angel = self.transform.localEulerAngles
        self.transform:SetParent(parent)
        self.transform.localPosition = pos
        self.transform.localScale = scale
        self.transform.localEulerAngles = angel
    end

    ---检查是否需要注册 OnDestroy
    self.behaviorHandlers = {}
    local needOnDestroy = false
    for i, behaviorFunName in pairs(Event) do
        if self[behaviorFunName] then
            needOnDestroy = true
            if behaviorFunName ~= Event.ON_DESTROY then
                table.insert(self.behaviorHandlers, behaviorFunName)
                AddEventListener(Stage,behaviorFunName, self[behaviorFunName], self)
            end
        end
    end
    if needOnDestroy == false then
        return
    end
    self.component = AddOrGetComponent(self.gameObject, Prayer.OnDestroyHandler) ---@type Prayer.OnDestroyHandler
    self.component.checkCall = function()
        self:RemoveBehaviorHandlers()
        if self.OnDestroy then
            self:OnDestroy()
        end
    end
end

---清理 BehaviorHandlers
function LuaObj:RemoveBehaviorHandlers()
    for i = 1, #self.behaviorHandlers do
        RemoveEventListener(Stage, self.behaviorHandlers[i], self[self.behaviorHandlers[i]], self)
    end
end

---@param luaObj LuaObj
---@return LuaObj
function LuaObj:AddEmbedLuaObj(luaObj)
    if not self.embedLuaObjs then
        self.embedLuaObjs = {} ---@type table<number, LuaObj>
    end
    table.insert(self.embedLuaObjs, luaObj)
    return luaObj
end

function LuaObj:Show()
    self.gameObject:SetActive(true)

    if self.embedLuaObjs then
        for i = 1, #self.embedLuaObjs do
            self.embedLuaObjs[i]:Show()
        end
    end
end

function LuaObj:Hide()
    self.gameObject:SetActive(false)
    if self.embedLuaObjs then
        for i = 1, #self.embedLuaObjs do
            self.embedLuaObjs[i]:Hide()
        end
    end
end


function LuaObj:Recycle()
    if self.prefabPath then
        RecyclePrefab(self.gameObject, self.prefabPath)
    end
    if self.embedLuaObjs then
        for i = 1, #self.embedLuaObjs do
            self.embedLuaObjs[i]:Recycle()
        end
        self.embedLuaObjs = nil
    end
    self.destroyed = true
    self:RemoveBehaviorHandlers()
end

function LuaObj:Destroy()
    GameObject.Destroy(self.gameObject)
    if self.embedLuaObjs then
        for i = 1, #self.embedLuaObjs do
            self.embedLuaObjs[i]:Destroy()
        end
        self.embedLuaObjs = nil
    end
    self.destroyed = true
end

return LuaObj