---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2020-05-05 15:58
---
---@class LuaScene:LuaScene
local LuaScene = class("LuaScene")

---@param scene UnityEngine.SceneManagement.Scene
---@param confName string
function LuaScene:Ctor(scene, confName)
    self.scene = scene
    self.sceneConfName = confName
    self.mainCamera = GetComponent.Camera(self:GetRootObjByName("Main Camera")) or Camera.main
    self.mainCamera.enabled = true
    self:ChangeMainCam(self.mainCamera)
end

---场景初始化
function LuaScene:Init()

end

---更换主相机
---@param cam UnityEngine.Camera
function LuaScene:ChangeMainCam(cam)
    local uiCamera = GetComponent.Canvas(Game.UICanvas).worldCamera
    if not uiCamera then
        return
    end
    local uiCamData = CameraExtensions.GetUniversalAdditionalCameraData(uiCamera)
    if self.mainCamera then
        LuaHelper.RemoveCameraFromStackList(self.mainCamera, uiCamera)
    end
    self.mainCamera = cam
    uiCamData.renderType = CameraRenderType.Overlay
    LuaHelper.AddCameraToStackList(self.mainCamera, uiCamera)
end

---@return UnityEngine.GameObject
function LuaScene:GetRootObjByName(name)
    local t = self.scene:GetRootGameObjects()
    for i = 0, t.Length-1 do
        --print("LuaScene:GetRootObjByName", i, t[i].name)
        if name == t[i].name then
            return t[i]
        end
    end
end

function LuaScene:Destroy()
    if self.destroyed == true then
        return
    end
    self.mainCamera.enabled = false
    self.destroyed = true
    self.scene = nil
    self.mainCamera = nil
end

function LuaScene:RemoveScene()
    SM.RemoveScene(self.scene)
end

return LuaScene