---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/4/25 15:29
--- 坐标跟随 场景上3D对象的 UI
---@class SceneUI:LuaObj
---@field New fun(prefabPath:string,bindGo:UnityEngine.GameObject,offsetV2:Vector2):SceneUI
local SceneUI = class("SceneUI", LuaObj)

function SceneUI:Ctor(prefabPath, bindGo, offsetV2, parent)
    SceneUI.super.Ctor(self, prefabPath, nil, parent or UILayerName.scene)

    self.rect = GetComponent.RectTransform(self.gameObject)
    self.bindGo = bindGo
    self.offsetV2 = offsetV2 or Vector2.zero

    self.stopUpdate = false
    self:Update()
    self.inScreen = false
end


function SceneUI:Update()

    if isnull(self.bindGo) == true then
        self:Recycle()
        return
    end
    if self.stopUpdate == true or self.destroyed == true or self.gameObject.activeSelf == false then
        return
    end

    local p = Happy.WorldToRectPos(self.bindGo.transform.position, self.rect.parent)

    p = p + self.offsetV2
    if self.inScreen then
        local fixX = p.x
        local fixY = p.y
        fixX = math.max(-self.screenSize.x/2 + self.sizeFix.x + self.size.x/2, fixX)
        fixX = math.min(self.screenSize.x/2 + self.sizeFix.y - self.size.x/2, fixX)

        fixY = math.max(-self.screenSize.y/2 + self.sizeFix.z + self.size.y/2, fixY)
        fixY = math.min(self.screenSize.y/2 + self.sizeFix.w - self.size.y/2, fixY)

        p = Vector2.New(fixX, fixY)
        --print("你妹啊1", self.screenSize.x, self.screenSize.y)
        --print("你妹啊2", self.size.x, self.size.y)
    end

    self.rect.anchoredPosition = p

end

---保持对象在屏幕中
---@param screenSizeFix Vector4
function SceneUI:KeepInScreen(boo, size, screenSizeFix)
    self.size = size or (self.rect.sizeDelta * self.rect.localScale.x)
    self.sizeFix = screenSizeFix or Vector4.New(0,0,62,-40)
    self.screenSize = GetComponent.RectTransform(Game.UICanvas.gameObject).sizeDelta
    self.inScreen = boo
end

function SceneUI:Show()
    SceneUI.super.Show(self)
    self:Update()
end


return SceneUI